version: '3.8'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_USER=gvdk
      - POSTGRES_DB=app4
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=gvdk
      - PG_HOST=db
      - PG_DATABASE=app4
      - PG_PASSWORD=abcd1234
      - PG_PORT=5432
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - /app/node_modules
      - ./worker:/app

volumes:
  db_data:
